[package]
name = "qodot"
version = "2.0.0"
authors = ["Josh Palmer <jpalmerwatkins@gmail.com>"]
edition = "2018"

[dependencies]
quarchitect = { path = "../quarchitect" }
gdnative = "0.8.1"

[lib]
crate-type = ["cdylib"]
